name: "Run go test"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'
      - 
        name: Install dependencies
        run: go get .
      - 
        name: Build
        run: go build -v ./...
      - 
        name: Run Unit Tests
        run: go test ./latitudesh -v -timeout 10m -run "TestProvider|TestFrameworkProvider"